"""Updated Party model to use party_name as primary key

Revision ID: 1395552b4bf2
Revises: e03721302cf1
Create Date: 2025-04-16 17:41:51.332609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1395552b4bf2'
down_revision = 'e03721302cf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('party',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('total_seats', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.alter_column('party_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'party', ['party_id'], ['name'])

    with op.batch_alter_table('state', schema=None) as batch_op:
        batch_op.alter_column('CM_party_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'party', ['CM_party_id'], ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('state', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('CM_party_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('party_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)

    op.drop_table('party')
    # ### end Alembic commands ###
