"""Add total_seats to Party model

Revision ID: 1504d065adca
Revises: 9dec8b824367
Create Date: 2025-04-01 02:42:58.473073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1504d065adca'
down_revision = '9dec8b824367'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('party', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_seats', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('party', schema=None) as batch_op:
        batch_op.drop_column('total_seats')

    # ### end Alembic commands ###
