"""Updated candidate model

Revision ID: 50f1faade4d9
Revises: 1395552b4bf2
Create Date: 2025-04-16 17:59:48.082717

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '50f1faade4d9'
down_revision = '1395552b4bf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('WON', 'LOST', name='candidate_status'),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('WON', 'LOST', name='candidate_status'),
               nullable=False)

    # ### end Alembic commands ###
