"""Initial clean migration

Revision ID: 9dec8b824367
Revises: 
Create Date: 2025-03-24 01:19:11.392719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dec8b824367'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('election', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_state_year_type', ['state_id', 'year', 'type'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('election', schema=None) as batch_op:
        batch_op.drop_constraint('unique_state_year_type', type_='unique')

    # ### end Alembic commands ###
