"""Fix FK: State.CM_party_id → party.name

Revision ID: c03f642981a0
Revises: 1504d065adca
Create Date: 2025-04-01 17:04:36.536391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c03f642981a0'
down_revision = '1504d065adca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.alter_column('party_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.drop_constraint('candidate_party_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'party', ['party_id'], ['name'])

    with op.batch_alter_table('constituency', schema=None) as batch_op:
        batch_op.drop_constraint('constituency_mp_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('constituency_mla_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key('fk_constituency_mla_id', 'candidate', ['mla_id'], ['id'], deferrable=True, use_alter=True)
        batch_op.create_foreign_key('fk_constituency_mp_id', 'candidate', ['mp_id'], ['id'], deferrable=True, use_alter=True)

    with op.batch_alter_table('party', schema=None) as batch_op:
        batch_op.drop_column('id')

    with op.batch_alter_table('state', schema=None) as batch_op:
        batch_op.alter_column('CM_party_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_constraint('state_CM_party_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'party', ['CM_party_id'], ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('state', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('state_CM_party_id_fkey', 'party', ['CM_party_id'], ['id'])
        batch_op.alter_column('CM_party_id',
               existing_type=sa.String(length=100),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('party', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))

    with op.batch_alter_table('constituency', schema=None) as batch_op:
        batch_op.drop_constraint('fk_constituency_mp_id', type_='foreignkey')
        batch_op.drop_constraint('fk_constituency_mla_id', type_='foreignkey')
        batch_op.create_foreign_key('constituency_mla_id_fkey', 'candidate', ['mla_id'], ['id'])
        batch_op.create_foreign_key('constituency_mp_id_fkey', 'candidate', ['mp_id'], ['id'])

    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('candidate_party_id_fkey', 'party', ['party_id'], ['id'])
        batch_op.alter_column('party_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)

    # ### end Alembic commands ###
