"""Initial migration

Revision ID: e03721302cf1
Revises: b7fe882f94bc
Create Date: 2025-04-05 13:11:28.412603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e03721302cf1'
down_revision = 'b7fe882f94bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.alter_column('const_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.alter_column('const_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
